graph TD
    COORD["Prof. Gabriel de Carvalho<br>(Coordenador Geral)"]
    COORD --> PBLP["Prof. Gabriel de Carvalho<br>(Coordenador de Projeto)"]

    PBLP --> PBPL["Pedro Boccaletti<br>Igor Amaral<br>(Co-Líderes de Programação)"]
    PBPL --> PBPROG[Programadores]

    PBLP --> PBDES["Ramon Lima<br>(Líder Criativo)"]
    PBDES --> PBGD[Game Designers]
    PBDES --> PBLD[Level Designers]
    PBDES --> PBUX[UX / UI Designers]

    PBLP --> PBART["Marcos Rodrigues<br>(Líder de Arte)"]
    PBART --> PBA2D[Artistas 2D]
    PBART --> PBANIM[Animadores]
    PBART --> PBMUS[Músicos]
    PBART --> PBAUD[Sound Designers]
